Feature-IOPS-2736-Primary-Sample-State
NHSDigital/NHSDigital-FHIR-Genomics-ImplementationGuide pull request #101
Opened 2024-08-02 10:01 UTC by KazeemHamzat

Feature-IOPS-2736-Primary-Sample-State

2024-08-02 13:28 UTC, omarisgreat reviewed
This may need holding off until we have a final valueset from adam (the sample type/state) discussions

2024-08-20 11:51 UTC, omarisgreat requested changes
Many inconsistencies in the MDS dataset, these need to be reviewed by Adam and the genomic SMEs to concretely defined the concepts

2024-08-20 11:51 UTC, omarisgreat commented on ConceptMap/ConceptMap-Genomics-primary-sample-state.json
> +  "purpose": "ConceptMap used for the translation and recording the concepts on method of sample preservation. This is intended for the element Specimen.condition",
This may be under Specimen.container.type depending on the type of information the MDS is specifying, needs clarification from Adam/the genomics SMEs

2024-08-20 11:51 UTC, omarisgreat commented on ConceptMap/ConceptMap-Genomics-primary-sample-state.json
> +              "display": "Evacuated blood collection tube (physical object)",
May need a more specific code to differentiate this from a normal BCT. Needs terminology input

2024-08-20 11:51 UTC, omarisgreat commented on ConceptMap/ConceptMap-Genomics-primary-sample-state.json
> +              "display": "Non-evacuated blood collection tube, EDTA",
Need to clarify whether we are specifying the tube type or the specimen conditions, e.g. tube with EDTA or specimen with EDTA

2024-08-20 11:51 UTC, omarisgreat commented on ConceptMap/ConceptMap-Genomics-primary-sample-state.json
> +              "equivalence": "unmatched"
May need to develop CodeSystem to capture codes not in SNOMED CT

2024-08-20 11:51 UTC, omarisgreat commented on ConceptMap/ConceptMap-Genomics-primary-sample-state.json
> +              "equivalence": "unmatched"
Would this be more like: 441652008 | Formalin-fixed paraffin-embedded tissue specimen (specimen) |

2024-08-20 11:51 UTC, omarisgreat commented on ConceptMap/ConceptMap-Genomics-primary-sample-state.json
> +              "display": "Blood tube (physical object)",
Might need a 261013005 | Fresh (qualifier value) | on a specimen type (ideally all would be qualifiers as they would qualify the state of a specimen

2024-08-20 11:51 UTC, omarisgreat commented on ConceptMap/ConceptMap-Genomics-primary-sample-state.json
> +              "display": "Tissue cassette (physical object)",
441479001 | Fresh tissue specimen (specimen) | seems more appropriate, though if we are coding container types, the concept type does not match

2024-08-20 11:51 UTC, omarisgreat commented on ConceptMap/ConceptMap-Genomics-primary-sample-state.json
> +              "display": "Non-evacuated blood collection tube, lithium heparin (physical object)",
Could also be 838941000000105 | Plasma specimen with lithium heparin (specimen) | if we are qualifying the specimen itself

2024-08-20 11:51 UTC, omarisgreat commented on ConceptMap/ConceptMap-Genomics-primary-sample-state.json
> +              "display": "Physical object (physical object)",
Might need higher level concept such as specimen state or specimen condition (neither in SNOMED CT)

2024-08-20 11:51 UTC, omarisgreat commented on ConceptMap/ConceptMap-Genomics-primary-sample-state.json
> +              "display": "Evacuated blood collection tube, ribonucleic acid stabilizer (physical object)",
Need to confirm this will always be within an evacuated BCT

2024-08-20 11:51 UTC, omarisgreat commented on ConceptMap/ConceptMap-Genomics-primary-sample-state.json
> +              "display": "Non-evacuated blood collection tube, EDTA",
Streck is a company which provides multiple tube types, need to confirm what exactly is being referenced here

2024-10-07 10:43 UTC, KazeemHamzat commented
May delay approval until the associated targetUri values are available in UKCore.

2024-10-07 14:35 UTC, omarisgreat approved these changes
Happy for you to merge in once the UK Core set is approved

2024-10-17 10:29 UTC, merged