Examples: Create a Test order for Mitochonria Disesases
NHSDigital/NHSDigital-FHIR-Genomics-ImplementationGuide pull request #19
Opened 2023-04-04 17:02 UTC by KazeemHamzat

Examples: Create a Test order for Mitochonria Disesases

2023-04-05 14:27 UTC, omarisgreat commented
> Examples: Create a Test order for Mitochonria Disesases

Link to PDF form this example is meant to represent (PID has been redacted and replaced with dummy data in the example): https://hscic365.sharepoint.com/:b:/r/sites/FHIRUKCore/Shared%20Documents/Products%20and%20Programmes/Products/Genomics/GMS%202022/Implementation%20Guide%20Content/Mitochondrial%20-%20referral%20example.pdf?csf=1&web=1&e=uf26RL

2023-04-05 17:56 UTC, KevinMayfield commented
I'm a little confused about this form. It appears to be both Test Order and Report. 
I'm presuming this form is used for both parts of the workflow and is updated during this workflow?

I'm concerned several resources contain information not present in the form. 
For example: we have Organization, PractitionerRole and Practitioner details. At most from the PDF I can see names, it would make sense to also see ODS, GMP, GMC codes. I would suggest following 
 FHIR-IDENT-03: from https://simplifier.net/guide/NHSDigital/Home/Policy/Identifiers.guide.md?version=current
 
Including these as resources may make this more difficult to implement.
 
Same applies to Condition. The Condition seems to be asserting points about the Condition which may risk clinical safety issues - at most we appear to have a name of a condition (not it's clinical or verification status, onset, etc). 

Should DiagnosticReport and Observations be included in the request, are they not the response to this request form?

I think this is also missing much of the structured data captured on the form, should a QuestionnaireReponse be present? 
(This form appears to be supportingInformation for the Test Order (ServiceRequest) and at early stages of this workflow, the DiagnosticReport wouldn't be present, so this can't be used)

2023-04-05 17:58 UTC, KevinMayfield requested changes
See previous comments

2023-04-06 09:03 UTC, omarisgreat requested changes
Additional changes needed to match PDF form

2023-04-06 09:03 UTC, omarisgreat commented on Bundle/UKCore-Bundle-MichaelChalmersRequest-Transaction-Example.json
> +            "extension": [
Missing additional contact extension for Victoria Nesbitt

2023-04-06 09:03 UTC, omarisgreat requested changes
Additional changes needed to match PDF form

2023-04-06 09:12 UTC, omarisgreat commented on Bundle/UKCore-Bundle-MichaelChalmersRequest-Transaction-Example.json
> +            "resourceType": "Condition",
Add Condition.note covering the note in the text box: "Spasticity and mobility problems since 2018"

2023-04-06 09:12 UTC, omarisgreat commented on Bundle/UKCore-Bundle-MichaelChalmersRequest-Transaction-Example.json
> +            "onsetDateTime": "2022-06-13T09:00:00Z",
Also add Condition.note covering the note in the text box: "Spasticity and mobility problems since 2018

2023-11-08 17:03 UTC, KazeemHamzat commented
No longer required.

2023-11-08 17:03 UTC, closed without merging